### ISSUE TITLE
[readCachedProjectGraph] ERROR: No cached ProjectGraph is available.

### ISSUE THREAD

**Issue by kyma** [TriPSs/nx-extend#172]
Getting this error relating to projectGraph not existing when trying to build Strapi.

Additional info: 

```
If you are leveraging `readCachedProjectGraph()` directly then you will need to refactor your usage to first ensure that
   the ProjectGraph is created by calling `await createProjectGraphAsync()` somewhere before attempting to read the data.
```

Callstack:

```
at readCachedProjectGraph (/Users/gannawayb/Documents/VS_Code/PROJECT/node_modules/@nrwl/workspace/node_modules/nx/src/project-graph/project-graph.js:28:15)
    at /Users/gannawayb/Documents/VS_Code/PROJECT/node_modules/@nx-extend/strapi/src/utils/create-package-json.js:12:121
    at Generator.next (<anonymous>)
    at /Users/gannawayb/Documents/VS_Code/PROJECT/node_modules/@nx-extend/strapi/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/gannawayb/Documents/VS_Code/PROJECT/node_modules/@nx-extend/strapi/node_modules/tslib/tslib.js:163:16)
    at createPackageJson (/Users/gannawayb/Documents/VS_Code/PROJECT/node_modules/@nx-extend/strapi/src/utils/create-package-json.js:11:20)
    at /Users/gannawayb/Documents/VS_Code/PROJECT/node_modules/@nx-extend/strapi/src/executors/build/build.impl.js:41:59
    at Generator.next (<anonymous>)
    at fulfilled (/Users/gannawayb/Documents/VS_Code/PROJECT/node_modules/@nx-extend/strapi/node_modules/tslib/tslib.js:164:62)
```

It was happening intermittently, but got worse when we migrated to the latest version of NX 16.10.0

Is there some additional step to take with the Strapi plugin to bring it into line?
It's not clear how to upgrade the version of this as migrate doesn't work...

**Comment by kyma** [comment]
```
 Node   : 20.8.0
   OS     : darwin-arm64
   npm    : 10.1.0
   
   nx (global)        : 16.10.0
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nrwl/workspace    : 15.9.2
   @nx/cypress        : 16.10.0
   @nx/devkit         : 16.10.0
   @nrwl/devkit       : 15.9.2
   @nx/esbuild        : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/next           : 16.10.0
   @nx/react          : 16.10.0
   @nx/storybook      : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/web            : 16.10.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @nx-extend/strapi : 3.5.2
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/workspace@15.9.2
     - @nrwl/devkit@15.9.2
   
   To fix this, run `nx migrate nx@16.10.0`
```

**Comment by kyma** [comment]
I've tried running nx migrate twice but it still says that I need to run it again

**Comment by TriPSs** [comment]
Could you update to `@nx-extend/strapi` 6.1.8

**Comment by kyma** [comment]
do you mean remove the two that are out of date?

**Comment by TriPSs** [comment]
Yea, and update `@nx-extend/strapi` :)

**Comment by kyma** [comment]
ok now I get a big stack of errors when running the build. Copying here as they don't mean much to me:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'semver/functions/lt' in '/Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/rc-cms/.cache/admin/src/components/AuthenticatedApp/utils'
    at /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/webpack/lib/Compilation.js:2022:28
    at /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/webpack/lib/NormalModuleFactory.js:817:13
    at eval (eval at create (/Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/webpack/lib/NormalModuleFactory.js:448:22
    at /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/webpack/lib/NormalModuleFactory.js:689:25
    at /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/webpack/lib/NormalModuleFactory.js:893:8
    at /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/webpack/lib/NormalModuleFactory.js:1013:5
resolve 'semver/functions/lt' in '/Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/rc-cms/.cache/admin/src/components/AuthenticatedApp/utils'
  Parsed request is a module
  using description file: /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/rc-cms/.cache/package.json (relative path: ./admin/src/components/AuthenticatedApp/utils)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/rc-cms/.cache/admin/src/components/AuthenticatedApp/utils/node_modules doesn't exist or is not a directory
      /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/rc-cms/.cache/admin/src/components/AuthenticatedApp/node_modules doesn't exist or is not a directory
      /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/rc-cms/.cache/admin/src/components/node_modules doesn't exist or is not a directory
      /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/rc-cms/.cache/admin/src/node_modules doesn't exist or is not a directory
      /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/rc-cms/.cache/admin/node_modules doesn't exist or is not a directory
      /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/rc-cms/.cache/node_modules doesn't exist or is not a directory
      /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/rc-cms/node_modules doesn't exist or is not a directory
      /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/node_modules doesn't exist or is not a directory
      looking for modules in /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules
        existing directory /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/semver
          using description file: /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/semver/package.json (relative path: .)
            using description file: /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/semver/package.json (relative path: ./functions/lt)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/semver/functions/lt doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/semver/functions/lt.js doesn't exist
              .jsx
                Field 'browser' doesn't contain a valid alias configuration
                /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/semver/functions/lt.jsx doesn't exist
              .react.js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/semver/functions/lt.react.js doesn't exist
              .ts
                Field 'browser' doesn't contain a valid alias configuration
                /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/semver/functions/lt.ts doesn't exist
              .tsx
                Field 'browser' doesn't contain a valid alias configuration
                /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/semver/functions/lt.tsx doesn't exist
              as directory
                /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/semver/functions/lt doesn't exist
      /Users/gannawayb/Documents/VS_Code/node_modules doesn't exist or is not a directory
      /Users/gannawayb/Documents/node_modules doesn't exist or is not a directory
      /Users/gannawayb/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve 'semver/functions/lt' in '/Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/rc-cms/.cache/admin/src/components/AuthenticatedApp/utils'
    at /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/webpack/lib/Compilation.js:2022:28
    at /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/webpack/lib/NormalModuleFactory.js:817:13
    at eval (eval at create (/Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/webpack/lib/NormalModuleFactory.js:448:22
    at /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/webpack/lib/NormalModuleFactory.js:689:25
    at /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/webpack/lib/NormalModuleFactory.js:893:8
    at /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/webpack/lib/NormalModuleFactory.js:1013:5
resolve 'semver/functions/lt' in '/Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/rc-cms/.cache/admin/src/components/AuthenticatedApp/utils'
  Parsed request is a module
  using description file: /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/rc-cms/.cache/package.json (relative path: ./admin/src/components/AuthenticatedApp/utils)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/rc-cms/.cache/admin/src/components/AuthenticatedApp/utils/node_modules doesn't exist or is not a directory
      /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/rc-cms/.cache/admin/src/components/AuthenticatedApp/node_modules doesn't exist or is not a directory
      /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/rc-cms/.cache/admin/src/components/node_modules doesn't exist or is not a directory
      /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/rc-cms/.cache/admin/src/node_modules doesn't exist or is not a directory
      /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/rc-cms/.cache/admin/node_modules doesn't exist or is not a directory
      /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/rc-cms/.cache/node_modules doesn't exist or is not a directory
      /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/rc-cms/node_modules doesn't exist or is not a directory
      /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/packages/node_modules doesn't exist or is not a directory
      looking for modules in /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules
        existing directory /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/semver
          using description file: /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/semver/package.json (relative path: .)
            using description file: /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/semver/package.json (relative path: ./functions/lt)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/semver/functions/lt doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/semver/functions/lt.js doesn't exist
              .jsx
                Field 'browser' doesn't contain a valid alias configuration
                /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/semver/functions/lt.jsx doesn't exist
              .react.js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/semver/functions/lt.react.js doesn't exist
              .ts
                Field 'browser' doesn't contain a valid alias configuration
                /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/semver/functions/lt.ts doesn't exist
              .tsx
                Field 'browser' doesn't contain a valid alias configuration
                /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/semver/functions/lt.tsx doesn't exist
              as directory
                /Users/gannawayb/Documents/VS_Code/RoyalCaninDogHub/node_modules/semver/functions/lt doesn't exist
      /Users/gannawayb/Documents/VS_Code/node_modules doesn't exist or is not a directory
      /Users/gannawayb/Documents/node_modules doesn't exist or is not a directory
      /Users/gannawayb/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
```

**Comment by TriPSs** [comment]
What version of strapi you have installed?

**Comment by kyma** [comment]
Strapi versions are saying 4.12.4

**Comment by TriPSs** [comment]
Could you update Strapi to `4.14.3`, clear the cache from old/previous builds and try again?

**Comment by kyma** [comment]
looks like the same big stack of errors as before unfortunately...

**Comment by TriPSs** [comment]
Could you try to remove the node_modules and .cache folders and try again. I'm not 100% sure that these errors are related to the nx-extend packages.

**Comment by kyma** [comment]
Same results. Can you think of anything else I can try here?

**Comment by TriPSs** [comment]
Hmm no sorry, I checked locally with my Strapi projects and cannot reproduce the issues you have.

**Comment by TriPSs** [comment]
@kyma do you still have this issues with the latest nx + nx-extend?
