### ISSUE TITLE
NPM ERR_DLOPEN_FAILED in /src/node_modules/@nx-extend/e2e-runner/node_modules/nx/src/native/native-bindings.js:244

### ISSUE THREAD

**Issue by jahusa02** [TriPSs/nx-extend#268]
With the newest @nx-extend/e2e-runner version, I'll get the following error:

```shell
08-May-2024 13:26:54 | npm ERR! command failed
08-May-2024 13:26:54 | npm ERR! command sh -c node ./bin/post-install
08-May-2024 13:26:54 | npm ERR! /src/node_modules/@nx-extend/e2e-runner/node_modules/nx/src/native/native-bindings.js:244
08-May-2024 13:26:54 | npm ERR!     throw loadError
08-May-2024 13:26:54 | npm ERR!     ^
08-May-2024 13:26:54 | npm ERR!
08-May-2024 13:26:54 | npm ERR! Error: /src/.nx/cache/18.3.4-nx.linux-x64-gnu.node: file too short
08-May-2024 13:26:54 | npm ERR!     at Module._extensions..node (node:internal/modules/cjs/loader:1465:18)
08-May-2024 13:26:54 | npm ERR!     at Module.load (node:internal/modules/cjs/loader:1206:32)
08-May-2024 13:26:54 | npm ERR!     at Module._load (node:internal/modules/cjs/loader:1022:12)
08-May-2024 13:26:54 | npm ERR!     at Module._load (/src/node_modules/@nx-extend/e2e-runner/node_modules/nx/src/native/index.js:58:27)
08-May-2024 13:26:54 | npm ERR!     at Module.require (node:internal/modules/cjs/loader:1231:19)
08-May-2024 13:26:54 | npm ERR!     at require (node:internal/modules/helpers:179:18)
08-May-2024 13:26:54 | npm ERR!     at  Object.<anonymous>  (/src/node_modules/@nx-extend/e2e-runner/node_modules/nx/src/native/native-bindings.js:184:31)
08-May-2024 13:26:54 | npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1369:14)
08-May-2024 13:26:54 | npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
08-May-2024 13:26:54 | npm ERR!     at Module.load (node:internal/modules/cjs/loader:1206:32) {
08-May-2024 13:26:54 | npm ERR!   code: 'ERR_DLOPEN_FAILED'
08-May-2024 13:26:54 | npm ERR! }
08-May-2024 13:26:54 | npm ERR!
08-May-2024 13:26:54 | npm ERR! Node.js v20.12.2
``` 

Here the output of nx report:

```shell
 NX   Report complete - copy this into the issue template

Node   : 20.13.0
OS     : linux-x64
npm    : 10.7.0

nx                 : 19.0.1
@nx/js             : 19.0.1
@nx/jest           : 19.0.1
@nx/linter         : 19.0.1
@nx/eslint         : 19.0.1
@nx/workspace      : 19.0.1
@nx/angular        : 19.0.1
@nx/cypress        : 19.0.1
@nx/devkit         : 19.0.1
@nx/esbuild        : 19.0.1
@nx/eslint-plugin  : 19.0.1
@nx/express        : 19.0.1
@nx/node           : 19.0.1
@nrwl/tao          : 19.0.1
@nx/vite           : 19.0.1
@nx/web            : 19.0.1
@nx/webpack        : 19.0.1
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/jest/plugin
@nx/vite/plugin
---------------------------------------
Community plugins:
@jsverse/transloco        : 7.4.0
@koliveira15/nx-sonarqube : 4.0.1
@ngrx/component-store     : 17.2.0
@ngrx/effects             : 17.2.0
@ngrx/entity              : 17.2.0
@ngrx/eslint-plugin       : 17.2.0
@ngrx/operators           : 17.2.0
@ngrx/router-store        : 17.2.0
@ngrx/schematics          : 17.2.0
@ngrx/store               : 17.2.0
@ngrx/store-devtools      : 17.2.0
@nx-extend/e2e-runner     : 9.0.1
@nx-tools/nx-container    : 6.0.0
ng-mocks                  : 14.12.2
ngx-matomo-client         : 6.1.3
```

**Comment by TriPSs** [comment]
This looks more like an issue with Nx, possibly using a different version than this package? 

The latest version only updates to the newest version of Nx if I remember correctly.

**Comment by TriPSs** [comment]
All packages are updated, could you give it a try?

**Comment by TriPSs** [comment]
I do not think this error is related to this package (simply because I also can't reproduce it with my projects), maybe one of the other packages did not update? (Also looks more like a Nx issues)

**Comment by dieguezz** [comment]
happening to me with nx 19.5.1
