### ISSUE TITLE
Error: [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.

### ISSUE THREAD

**Issue by creaux** [TriPSs/nx-extend#289]
Hello,

I'm getting following error after clear init. Apart from issue itself how easily to debug it?

```
$ strapi develop
✔ Cleaning dist dir (4ms)
⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (105ms)
⠸ Creating admin/Users/creaux/Development/inbdm/node_modules/@nx-extend/strapi/node_modules/@nx/workspace/node_modules/nx/src/project-graph/project-graph.js:31
        throw new Error((0, strip_indents_1.stripIndents) `
              ^

Error: [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.

If you are leveraging \`readCachedProjectGraph()\` directly then you will need to refactor your usage to first ensure that
the ProjectGraph is created by calling \`await createProjectGraphAsync()\` somewhere before attempting to read the data.

If you encounter this error as part of running standard \`nx\` commands then please open an issue on https://github.com/nrwl/nx
    at readCachedProjectGraph (/Users/creaux/Development/inbdm/node_modules/@nx-extend/strapi/node_modules/@nx/workspace/node_modules/nx/src/project-graph/project-graph.js:31:15)
    at withNx (/Users/creaux/Development/inbdm/packages/strapi/src/with-nx.ts:11:46)
    at module.exports (/Users/creaux/Development/inbdm/apps/strapi/src/admin/webpack.config.js:6:10)
    at Object.mergeConfigWithUserConfig (/Users/creaux/Development/inbdm/node_modules/@strapi/admin/_internal/node/webpack/config.ts:209:14)
    at <anonymous> (/Users/creaux/Development/inbdm/node_modules/@strapi/admin/_internal/node/webpack/build.ts:11:25)

Node.js v20.9.0
error: script "develop" exited with code 1
```

```
❯ nx report

 NX   Report complete - copy this into the issue template

Node   : 20.9.0
OS     : darwin-arm64
bun    : 1.1.13

nx (global)        : 19.1.1
nx                 : 19.1.1
@nx/js             : 19.1.1
@nx/jest           : 19.1.1
@nx/linter         : 19.1.1
@nx/eslint         : 19.1.1
@nx/workspace      : 19.1.1
@nx/devkit         : 19.1.1
@nx/esbuild        : 19.1.1
@nx/eslint-plugin  : 19.1.1
@nx/node           : 19.1.1
@nrwl/tao          : 19.1.1
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/jest/plugin
---------------------------------------
Community plugins:
@nx-extend/strapi                   : 10.0.3
```

**Comment by TriPSs** [comment]
Please update to the latest version of Nx, that should solve the issue.

**Comment by creaux** [comment]
Thanks for prompt response. This worked. However lead me to another issue: #291
