### ISSUE TITLE
ESLint 9.x expects eslint.config.json

### ISSUE THREAD

**Issue by itmustbejj** [TriPSs/nx-extend#350]
I came across this [similar issue](https://github.com/nrwl/nx/issues/28404) trying to generate a lib using the `nx-extend/pulumi` plugin after updating nx:
```
 NX   Could not find root flat config file

Error: Could not find root flat config file
    at getRootESLintFlatConfigFilename (/Users/user/my/path/node_modules/@nx/eslint/src/utils/flat-config.js:18:11)
    at lintConfigHasOverride (/Users/user/my/path/node_modules/@nx/eslint/src/generators/utils/eslint-file.js:177:164)
    at addLint (/Users/user/my/path/node_modules/@nx/js/src/generators/library/library.js:237:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async libraryGeneratorInternal (/Users/user/my/path/node_modules/@nx/js/src/generators/library/library.js:74:30)
    at async /Users/user/my/path/node_modules/nx/src/command-line/generate/generate.js:238:26
    at async handleErrors (/Users/user/my/path/node_modules/nx/src/utils/handle-errors.js:9:24)
    at async Object.handler (/Users/user/my/path/node_modules/nx/src/command-line/generate/command-object.js:14:22)
```

Luckily the migration is easy with `npx nx g @nx/eslint:convert-to-flat-config`, but the generator in these plugins will need to be updated to stop using `.eslintrc.json`.

**Comment by itmustbejj** [comment]
I reverted to eslint v8.57.0 and everything works for now. Sorry for the noise.
