### ISSUE TITLE
stapi build fails with @nx-extend/strapi "^3.0.2"

### ISSUE THREAD

**Issue by stefangoor** [TriPSs/nx-extend#67]
Hi there,

I have been trying to recreate a monorepo that I have and the strapi build fails with the newer project.

The new project has `"@nx-extend/strapi": "^3.0.2"` in the package.json and when I run `nx build <stapi-package-name>` on a newly created stapi package it fails with the following:

```
$ nx build strapi-pkg --verbose

> nx run strapi-pkg:build

Starting the compilation for TypeScript files in packages/strapi-pkg/src

 >  NX   Debug Failure.


Error: Debug Failure.
    at /Users/me/dev/monorepo/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:19675:89
    at String.replace (<anonymous>)
    at formatStringFromArgs (/Users/me/dev/monorepo/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:19675:21)
    at Object.createCompilerDiagnostic (/Users/me/dev/monorepo/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:19789:20)
    at tryReadFile (/Users/me/dev/monorepo/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:40100:40)
    at Object.getParsedCommandLineOfConfigFile (/Users/me/dev/monorepo/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:40046:30)
    at module.exports (/Users/me/dev/monorepo/node_modules/@strapi/typescript-utils/lib/utils/resolve-config-options.js:9:43)
    at Object.run (/Users/me/dev/monorepo/node_modules/@strapi/typescript-utils/lib/compilers/basic.js:19:55)
    at Object.module.exports [as compile] (/Users/me/dev/monorepo/node_modules/@strapi/typescript-utils/lib/compile.js:13:12)
    at /Users/me/dev/monorepo/node_modules/@nx-extend/strapi/src/executors/build/build.impl.js:26:42

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "strapi-pkg:build" failed

   Failed tasks:

   - strapi-pkg:build

   Hint: run the command with --verbose for more details.
```

Reverting to version ^2.1.2 solves the issue.

I'm not sure what is causing the issue above as there is very little in the error messages.  Any ideas what is causing this?  For the moment I will stick with version 2.1.2.

Thanks

**Comment by TriPSs** [comment]
What version of `@strapi/strapi` are you using? 

Version 3 of `@nx-extend/strapi` builds the project itself/reuses code from Strapi instead of calling the CLI.

**Comment by stefangoor** [comment]
Hi TriPSs,

Thanks for the reply.

I am using the following:

Node v16.14.2
NPM v8.7.0
"@strapi/strapi": "4.3.6",

The issue can be reproduced with the following series of commands:

```
npx create-nx-workspace@latest nx-strapi-monorepo --preset=ts --nxCloud=false
cd nx-strapi-monorepo
npm install -D @nx-extend/strapi
nx g @nx-extend/strapi:init.  #gave it the name strapi
nx build strapi --verbose
```

Please let me know if you would like any further information.

Thanks

**Comment by TriPSs** [comment]
Thanks for the detailed reproduction steps, found out that the `sourceRoot` is not set correctly, if you change it from `packages/strapi/src` to `packages/strapi` it works.

**Comment by TriPSs** [comment]
Thanks for reporting, this is fixed with in `3.0.3`

**Comment by stefangoor** [comment]
Thanks so much for sorting this out.  The patch fix worked.

I did hit another slight issue when building strapi with this version.  It gave the following error:

```
$ nx build strapi-pkg --verbose

> nx run strapi-pkg:build


 >  NX   Cannot find module 'react-select/animated'

   Require stack:
   - /Users/me/dev/nx-repo/node_modules/@strapi/admin/webpack.alias.js
   - /Users/me/dev/nx-repo/node_modules/@strapi/admin/webpack.config.js
   - /Users/me/dev/nx-repo/node_modules/@strapi/admin/utils/get-custom-webpack-config.js
   - /Users/me/dev/nx-repo/node_modules/@strapi/admin/utils/index.js
   - /Users/me/dev/nx-repo/node_modules/@strapi/admin/index.js
   - /Users/me/dev/nx-repo/node_modules/@strapi/strapi/lib/commands/builders/admin.js
   - /Users/me/dev/nx-repo/node_modules/@strapi/strapi/lib/commands/builders/index.js
   - /Users/me/dev/nx-repo/node_modules/@nx-extend/strapi/src/executors/build/build.impl.js
   - /Users/me/dev/nx-repo/node_modules/nx/src/config/workspaces.js
   - /Users/me/dev/nx-repo/node_modules/nx/src/command-line/run.js
   - /Users/me/dev/nx-repo/node_modules/nx/bin/run-executor.js

Error: Cannot find module 'react-select/animated'
Require stack:
- /Users/me/dev/nx-repo/node_modules/@strapi/admin/webpack.alias.js
- /Users/me/dev/nx-repo/node_modules/@strapi/admin/webpack.config.js
- /Users/me/dev/nx-repo/node_modules/@strapi/admin/utils/get-custom-webpack-config.js
- /Users/me/dev/nx-repo/node_modules/@strapi/admin/utils/index.js
- /Users/me/dev/nx-repo/node_modules/@strapi/admin/index.js
- /Users/me/dev/nx-repo/node_modules/@strapi/strapi/lib/commands/builders/admin.js
- /Users/me/dev/nx-repo/node_modules/@strapi/strapi/lib/commands/builders/index.js
- /Users/me/dev/nx-repo/node_modules/@nx-extend/strapi/src/executors/build/build.impl.js
- /Users/me/dev/nx-repo/node_modules/nx/src/config/workspaces.js
- /Users/me/dev/nx-repo/node_modules/nx/src/command-line/run.js
- /Users/me/dev/nx-repo/node_modules/nx/bin/run-executor.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at /Users/me/dev/nx-repo/node_modules/@strapi/admin/webpack.alias.js:51:25
    at Array.reduce (<anonymous>)
    at Object.<anonymous> (/Users/me/dev/nx-repo/node_modules/@strapi/admin/webpack.alias.js:50:12)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

but that was easily fixed by installing the package:

`npm i react-select`

Thanks again for your help with this and for the quick fix.

**Comment by TriPSs** [comment]
Thas weird as `react-select` is a dep of `@strapi/helper-plugin` so it should be installed.

**Comment by stefangoor** [comment]
Yeah I though it was a bit strange too as I can see the references to it in package-lock.json but run the npm install solves it anyway.  Thanks again for your help.
